z<- rnorm(50)
plot(z, pch=11)
hist(z, xlim=c(-5,5), ylim=c(0,15),
write.csv(iris, "iris.csv")
myris<- read.table("iris.csv", header=TRUE)
install.packages('RCurl')
library(RCurl)
u <- getURL ("http://vincentarelbundock.github.io/Rdatasets/csv/Ecdat/Computers.csv" )
c_prices<- read.csv(text = u)
head(c_prices)
hist(c_prices$hd)
hist(c_prices$ozone)
attach(airquality)
head(airquality)
hist(Ozone)
boxplot(Ozone~Month,data=airquality,main="Different boxplots for each month",xlab="Month Number",ylab="Ozone", col = c("red", "orange", "yellow", "green", "blue"))
library('ggmap')
qmap("Toronto")
qmap("M4Y1L8", zoom=18, maptype="hybrid")
?qmap
qmap("M4Y1L8", zoom=18, maptype="satellite")
mapdist(from="Toronto", to=c("Montreal","Ottawa"), , mode=c("driving"))
